apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: payment-outbox-mongo
spec:
  members: 1 
  type: ReplicaSet
  version: "8.0.0" 
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef: 
        name: admin-mongo-credentials
      roles:
        - name: clusterAdmin
          db: admin
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: admin-mongo-scram
    - name: yana
      db: outbox
      passwordSecretRef: 
        name: user-mongo-credentials
      roles:
        - name: dbOwner  
          db: outbox
      scramCredentialsSecretName: yana-mongo-scram 
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume 
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 200Mi 