apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: yaaanni/api-gateway:v1
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60  
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 65  
            periodSeconds: 10
            failureThreshold: 3
          env:
            - name: EXTERNAL_USER_SERVICE_URL
              value: "http://user-service:80" 
            - name: EXTERNAL_AUTH_SERVICE_URL
              value: "http://auth-service:80"
            - name: EXTERNAL_ORDER_SERVICE_URL
              value: "http://order-service:80"
            - name: EXTERNAL_PAYMENT_SERVICE_URL
              value: "http://payment-service:80"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: order-service-secrets
                  key: JWT_SECRET

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
spec:
  rules:
  - host: shop.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway 
            port:
              number: 80     