apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisReplication
metadata:
  name: user-redis
spec:
  clusterSize: 1
  kubernetesConfig:
    image: redis:7
    redisSecret:
      name: user-redis-credentials
      key: password
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 200Mi